# Generated by Django 2.2.5 on 2019-10-30 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='안건과 관련된 회의 내용을 작성하는 부분입니다.')),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('is_parent_note', models.BooleanField(default=True)),
                ('has_children', models.BooleanField(default=False)),
                ('containing_block_types', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ml_speech_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('admins', models.ManyToManyField(related_name='workspace_admins', to='meetingoverflow.Profile')),
                ('members', models.ManyToManyField(related_name='workspace_members', to='meetingoverflow.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('is_parent_note', models.BooleanField(default=True)),
                ('assignees', models.ManyToManyField(to='meetingoverflow.Profile')),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Note')),
                ('parent_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetingoverflow.Agenda')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('is_parent_note', models.BooleanField(default=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Note')),
                ('parent_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetingoverflow.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('is_parent_note', models.BooleanField(default=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Note')),
                ('parent_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetingoverflow.Agenda')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='participants',
            field=models.ManyToManyField(to='meetingoverflow.Profile'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='meetingoverflow.Tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Workspace'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(null=True, upload_to='')),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('is_parent_note', models.BooleanField(default=True)),
                ('image_caption', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Note')),
                ('parent_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetingoverflow.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('is_parent_note', models.BooleanField(default=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Note')),
                ('parent_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetingoverflow.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('is_parent_note', models.BooleanField(default=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Note')),
                ('parent_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetingoverflow.Agenda')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetingoverflow.Note'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='parent_agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetingoverflow.Agenda'),
        ),
    ]
