# Generated by Django 2.1.7 on 2019-10-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingoverflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='안건과 관련된 회의 내용을 작성하는 부분입니다.')),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('note_id', models.IntegerField()),
                ('parent_agenda_id', models.IntegerField()),
                ('is_parent_note', models.BooleanField(default=True)),
                ('has_children', models.BooleanField(default=False)),
                ('containing_block_types', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('note_id', models.IntegerField()),
                ('parent_agenda_id', models.IntegerField()),
                ('is_parent_note', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('note_id', models.IntegerField()),
                ('parent_agenda_id', models.IntegerField()),
                ('is_parent_note', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(null=True, upload_to='')),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('note_id', models.IntegerField()),
                ('parent_agenda_id', models.IntegerField()),
                ('is_parent_note', models.BooleanField(default=True)),
                ('image_caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('note_id', models.IntegerField()),
                ('parent_agenda_id', models.IntegerField()),
                ('is_parent_note', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('note_id', models.IntegerField()),
                ('parent_agenda_id', models.IntegerField()),
                ('is_parent_note', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('layer_x', models.IntegerField(default=0)),
                ('layer_y', models.IntegerField(default=0)),
                ('note_id', models.IntegerField()),
                ('parent_agenda_id', models.IntegerField()),
                ('is_parent_note', models.BooleanField(default=True)),
                ('assignees', models.ManyToManyField(to='meetingoverflow.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='notes',
            field=models.ManyToManyField(null=True, to='meetingoverflow.Note'),
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='admins',
        ),
        migrations.AddField(
            model_name='workspace',
            name='admins',
            field=models.ManyToManyField(related_name='workspace_admins', to='meetingoverflow.Profile'),
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspace_members', to='meetingoverflow.Profile'),
        ),
    ]
