# Generated by Django 2.1.7 on 2019-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingoverflow', '0002_auto_20191026_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='notes',
            field=models.ManyToManyField(to='meetingoverflow.Note'),
        ),
    ]
