# Generated by Django 2.1.7 on 2019-10-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingoverflow', '0004_auto_20191028_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(null=True, to='meetingoverflow.Tag'),
        ),
    ]
