# Generated by Django 2.1.7 on 2019-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingoverflow', '0005_auto_20191028_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='participants',
        ),
        migrations.AddField(
            model_name='note',
            name='participants',
            field=models.ManyToManyField(to='meetingoverflow.Profile'),
        ),
    ]
