# Generated by Django 2.1.7 on 2019-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingoverflow', '0006_auto_20191028_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='meetingoverflow.Tag'),
        ),
    ]
