# Generated by Django 2.1.7 on 2019-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingoverflow', '0007_auto_20191028_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='meetingoverflow.Tag'),
        ),
    ]
